In [1]:
import pandas as pd
import numpy as  np

In [2]:
df=pd.read_csv('HousePrices.csv')
df

Id  Dwell_Type Zone_Class  LotFrontage  LotArea Road_Type Alley  \
0       1          60         RL         65.0     8450      Pave   NaN   
1       2          20         RL         80.0     9600      Pave   NaN   
2       3          60         RL         68.0    11250      Pave   NaN   
3       4          70         RL         60.0     9550      Pave   NaN   
4       5          60         RL         84.0    14260      Pave   NaN   
...   ...         ...        ...          ...      ...       ...   ...   
2068  942          60         RL          NaN     8755      Pave   NaN   
2069  943          90         RL         63.0     7711      Pave   NaN   
2070  944          90         RL        313.0    25000      Pave   NaN   
2071  945          20         RL         52.0    14375      Pave   NaN   
2072  946          50         RM         98.0     8820      Pave   NaN   

     Property_Shape LandContour Utilities  ... PoolArea PoolQC  Fence  \
0               Reg         Lvl    AllPub  ...        0    NaN    NaN   
1               Reg         Lvl    AllPub  ...        0    NaN    NaN   
2               IR1         Lvl    AllPub  ...        0    NaN    NaN   
3               IR1         Lvl    AllPub  ...        0    NaN    NaN   
4               IR1         Lvl    AllPub  ...        0    NaN    NaN   
...             ...         ...       ...  ...      ...    ...    ...   
2068            IR1         Lvl    AllPub  ...        0    NaN  GdPrv   
2069            IR1         Lvl    AllPub  ...        0    NaN    NaN   
2070            Reg         Low    AllPub  ...        0    NaN    NaN   
2071            IR1         Lvl    NoSeWa  ...        0    NaN    NaN   
2072            Reg         Lvl    AllPub  ...        0    NaN   MnWw   

     MiscFeature MiscVal MoSold YrSold  SaleType  SaleCondition  \
0            NaN       0      2   2008        WD         Normal   
1            NaN       0      5   2007        WD         Normal   
2            NaN       0      9   2008        WD         Normal   
3            NaN       0      2   2006        WD        Abnorml   
4            NaN       0     12   2008        WD         Normal   
...          ...     ...    ...    ...       ...            ...   
2068         NaN       0      6   2009        WD         Normal   
2069         NaN       0      8   2007       Oth        Abnorml   
2070         NaN       0      6   2007        WD         Normal   
2071         NaN       0      1   2009       COD        Abnorml   
2072         NaN       0      9   2009        WD         Normal   

      Property_Sale_Price  
0                  208500  
1                  181500  
2                  223500  
3                  140000  
4                  250000  
...                   ...  
2068               214000  
2069               150000  
2070               143000  
2071               137500  
2072               124900  

[2073 rows x 81 columns]

In [3]:
df.isnull().sum()

Id                       0
Dwell_Type               0
Zone_Class               0
LotFrontage            320
LotArea                  0
                      ... 
MoSold                   0
YrSold                   0
SaleType                 0
SaleCondition            0
Property_Sale_Price      0
Length: 81, dtype: int64

In [4]:
missing_values=df.columns[df.isnull().any()]

df[missing_values].isnull().sum()

LotFrontage      320
Alley           1944
MasVnrType        14
MasVnrArea        14
BsmtQual          59
BsmtCond          59
BsmtExposure      61
BsmtFinType1      59
BsmtFinType2      60
Electrical         1
FireplaceQu      988
GarageType       113
GarageYrBlt      113
GarageFinish     113
GarageQual       113
GarageCond       113
PoolQC          2065
Fence           1669
MiscFeature     1993
dtype: int64

In [5]:
df['LotFrontage'].fillna(df['LotFrontage'].mean(),inplace=True)
df['MasVnrArea'].fillna(df['MasVnrArea'].mean(),inplace=True)

In [6]:
x=df[['Dwell_Type','LotFrontage', 'LotArea','OverallQual','OverallCond','MasVnrArea',
'BsmtFinSF1','BsmtUnfSF','TotalBsmtSF','1stFlrSF','2ndFlrSF','GrLivArea','GarageArea',
'WoodDeckSF', 'OpenPorchSF']]
y=df['Property_Sale_Price']

In [7]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x,y)

LinearRegression()

In [8]:
model.score(x,y)

0.7301484228992423

In [9]:
house=model.predict([[70,85,12000,6,8,100,520,430,1024,950,850,1800,700,150,42]])
house

array([219696.36904046])

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.25,random_state=0)

In [11]:
from sklearn.linear_model import LinearRegression
lin_reg_mod = LinearRegression()
lin_reg_mod.fit(X_train, y_train)

LinearRegression()

In [12]:
pred = lin_reg_mod.predict(X_test)
pred

array([100212.13951268, 162361.70095778, 258052.4005472 , 169839.95820109,
       109017.5165217 , 180333.33864283, 100641.98784044, 221430.91705674,
       222596.82410993, 149597.21924243, 117111.80687596, 218229.37922961,
       341928.16515755, 168354.12960485, 197694.0173465 , 253914.67858693,
       121952.13169696, 200683.62836471, 128386.86537668,  96547.70162494,
       169382.44072569, 184304.9251493 , 150741.56942364, 163378.07067669,
       189353.98635029, 207584.96724356, 201192.93326243,  75800.37555707,
       235754.59892216, 201168.64654963, 282613.00474524, 192710.53620389,
       137449.1956226 , 265444.38884026, 121455.4857672 , 135863.03288609,
        90027.08353817, 149311.17505845, 135477.29248523,  99310.01471834,
       196087.88766155, 139733.56338756, 133602.57948928,  76729.14012143,
       198470.99921424, 231459.97072044,  80831.1823594 , 133032.86537346,
       109253.50473008, 198229.37017955, 101805.76539243, 201183.20060692,
       315896.41443068, 1

In [13]:
from sklearn import metrics
test_set_r2 = metrics.r2_score(y_test, pred)
print(test_set_r2)

0.7630222164561856


In [14]:
housing_price=lin_reg_mod.predict([[70,85,12000,6,8,100,520,430,1024,950,850,1800,700,150,42]])
housing_price

array([221263.24355059])